name: Deploy Azure Function App

on:
  push:
    branches:
      - main  # Deploys when code is pushed to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      # Checkout the repository
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      # Set up Node.js (if using JavaScript/TypeScript for Azure Functions)
      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Use Node.js version that matches Azure Function runtime

      # Install dependencies (if applicable)
      - name: 'Install dependencies'
        run: npm install
        working-directory: ./ # Adjust if your function app is in a subdirectory

      # Log in to Azure using a service principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9024383B7716461383948BEC8B466664 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FE37AE8ECDFB46BBA83F095B2D72F8C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22701192172F4A2CA7AB3B4BD4CDD297 }}

      # Deploy to Azure Functions
      - name: 'Deploy Azure Function App'
        uses: azure/functions-action@v1
        with:
          app-name: 'dev-demo-functions-app'  # Azure Function App name
          package: '.'  # Path to your function app's code, adjust if needed
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Azure Function App publish profile secret

